# .github/labeler.yml 
# components:
#   - changed-files:
#       - any-glob-to-any-file: src/components/*
label test new:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
  - head-branch:
      - '^test-'
