# name: PR Labeler

# on:
#   pull_request_target:
#     types: [opened, synchronize]
#   workflow_dispatch:  # This enables manual triggering from the Actions tab

# jobs:
#   label:
#     name: Add PR labels
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v4
#       - uses: actions/labeler@v5
#         with:
#           repo-token: '${{ secrets.GITHUB_TOKEN }}'
#           sync-labels: true
name: Labeler Test issue 870

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    #   issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: chiranjib-swain/labeler@feature/improve-labeler-permissions
        with:
          sync-labels: true
